apiVersion: apps/v1
kind: Deployment
metadata:
  name: restricted-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restricted
  template:
    metadata:
      labels:
        app: restricted
    spec:
      containers:
        - name:  alpine
          image: alpine:latest
          args: [sleep, 1000d]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
